# Data Collection Notebook

## Objectives

* Fetch data from Kaggle and save as raw data
* Inspect the data and save it under outputs/datasets/collection

## Inputs

* Kaggle json file for data download. This file includes the authentication token. 

## Outputs

* Inputs/datasets/raw folder, which includes the downloaded raw data
* Outputs/datasets/collection folder, which includes the data downloaded after initial screening

## Imports and Setup

In [1]:
import os
import pandas as pd

---

# Change working directory

* Define and set working directory

In [3]:
from pathlib import Path
import os

try:
    NOTEBOOK_DIR = Path(__file__).resolve().parent
except NameError:
    # Jupyter notebook
    NOTEBOOK_DIR = Path(os.getcwd()).resolve()

# Walk up until we find the project marker
PROJECT_ROOT = NOTEBOOK_DIR
while not (PROJECT_ROOT / "pyproject.toml").exists() and not (PROJECT_ROOT / ".git").exists():
    if PROJECT_ROOT.parent == PROJECT_ROOT:
        raise RuntimeError("Project root not found")
    PROJECT_ROOT = PROJECT_ROOT.parent

PROJECT_ROOT

PosixPath('/Users/mehtap/dev/commit-trial-repo-dev')

# Fetch Data from Kaggle

Install Kaggle package to fetch data

In [4]:
! pip install kaggle==1.5.12

Collecting kaggle==1.5.12
  Downloading kaggle-1.5.12.tar.gz (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 3.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: six>=1.10 in /Users/mehtap/dev/commit-trial-repo-dev/.venv/lib/python3.12/site-packages (from kaggle==1.5.12) (1.17.0)
Collecting certifi (from kaggle==1.5.12)
  Obtaining dependency information for certifi from https://files.pythonhosted.org/packages/e6/ad/3cc14f097111b4de0040c83a525973216457bbeeb63739ef1ed275c1c021/certifi-2026.1.4-py3-none-any.whl.metadata
  Using cached certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: python-dateutil in /Users/mehtap/dev/commit-trial-repo-dev/.venv/lib/python3.12/site-packages (from kaggle==1.5.12) (2.9.0.post0)
Collecting requests (from kaggle==1.5.12)
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/1e/db/4254e3eabe8020b458f1a747140d32277ec7a271daf1d235b70dc0b4e6e3/requests-2.32.5-py3-none-any.whl.metadata
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm (from kaggle==1.5.12)
  Obtaining dependency information for tqdm from https://files.pythonhosted.org/packages/d0/30/dc54f88dd4a2b5dc8a0279bdd7270e735851848b762aeb1c1184ed1f6b14/tqdm-4.67.1-py3-none-any.whl.metadata
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 5.3 MB/s eta 0:00:00
Collecting python-slugify (from kaggle==1.5.12)
  Obtaining dependency information for python-slugify from https://files.pythonhosted.org/packages/a4/62/02da182e544a51a5c3ccf4b03ab79df279f9c60c5e82d5e8bec7ca26ac11/python_slugify-8.0.4-py2.py3-none-any.whl.metadata
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting urllib3 (from kaggle==1.5.12)
  Obtaining dependency information for urllib3 from https://files.pythonhosted.org/packages/39/08/aaaad47bc4e9dc8c725e68f9d04865dbcb2052843ff09c97b08904852d84/urllib3-2.6.3-py3-none-any.whl.metadata
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle==1.5.12)
  Obtaining dependency information for text-unidecode>=1.3 from https://files.pythonhosted.org/packages/a6/a5/c0b6468d3824fe3fde30dbb5e1f687b291608f9473681bbf7dabbf5a87d7/text_unidecode-1.3-py2.py3-none-any.whl.metadata
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting charset_normalizer<4,>=2 (from requests->kaggle==1.5.12)
  Obtaining dependency information for charset_normalizer<4,>=2 from https://files.pythonhosted.org/packages/f3/85/1637cd4af66fa687396e757dec650f28025f2a2f5a5531a3208dc0ec43f2/charset_normalizer-3.4.4-cp312-cp312-macosx_10_13_universal2.whl.metadata
  Downloading charset_normalizer-3.4.4-cp312-cp312-macosx_10_13_universal2.whl.metadata (37 kB)
Collecting idna<4,>=2.5 (from requests->kaggle==1.5.12)
  Obtaining dependency information for idna<4,>=2.5 from https://files.pythonhosted.org/packages/0e/61/66938bbb5fc52dbdf84594873d5b51fb1f7c7794e9c0f5bd885f30bc507b/idna-3.11-py3-none-any.whl.metadata
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Using cached certifi-2026.1.4-py3-none-any.whl (152 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 9.8 MB/s eta 0:00:00
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 10.6 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.4-cp312-cp312-macosx_10_13_universal2.whl (208 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.4/208.4 kB 11.3 MB/s eta 0:00:00
Downloading idna-3.11-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 9.3 MB/s eta 0:00:00
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.2/78.2 kB 9.7 MB/s eta 0:00:00
Building wheels for collected packages: kaggle
  Building wheel for kaggle (pyproject.toml) ... done
  Created wheel for kaggle: filename=kaggle-1.5.12-py3-none-any.whl size=73076 sha256=f911977201fad178e005e4795c2267267eef3727d19b1827c38683a96001cbff
  Stored in directory: /Users/mehtap/Library/Caches/pip/wheels/f5/69/4d/d701fc604b9fb09be59718b4056fd5556a22588ce1f25dd090
Successfully built kaggle
Installing collected packages: text-unidecode, urllib3, tqdm, python-slugify, idna, charset_normalizer, certifi, requests, kaggle
Successfully installed certifi-2026.1.4 charset_normalizer-3.4.4 idna-3.11 kaggle-1.5.12 python-slugify-8.0.4 requests-2.32.5 text-unidecode-1.3 tqdm-4.67.1 urllib3-2.6.3

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: pip install --upgrade pip

Add token obtained from Kaggle for data download

In [ ]:
os.environ['KAGGLE_CONFIG_DIR'] = os.getcwd()
! chmod 600 kaggle.json

Download the housing-prices-data from Kaggle and save it under inputs/datasets/raw folder.

In [ ]:
KaggleDatasetPath = "codeinstitute/housing-prices-data"
DestinationFolder = "inputs/datasets/raw"
! kaggle datasets download -d {KaggleDatasetPath} -p {DestinationFolder}

Downloading housing-prices-data.zip to inputs/datasets/raw
  0%|                                               | 0.00/49.6k [00:00<?, ?B/s]
100%|███████████████████████████████████████| 49.6k/49.6k [00:00<00:00, 574kB/s]

---

Unzip the downloaded file and delete the zip file

In [ ]:
! unzip {DestinationFolder}/*.zip -d {DestinationFolder} \
    && rm {DestinationFolder}/*.zip

Archive:  inputs/datasets/raw/housing-prices-data.zip
  inflating: inputs/datasets/raw/house-metadata.txt
  inflating: inputs/datasets/raw/house-price-20211124T154130Z-001/house-price/house_prices_records.csv
  inflating: inputs/datasets/raw/house-price-20211124T154130Z-001/house-price/inherited_houses.csv

# Load and Inspect Data

## Load and inspect `house_prices_records` data.

Load data

In [ ]:
df = pd.read_csv(f"inputs/datasets/raw/house-price-20211124T154130Z-001/house-price/house_prices_records.csv")
df.head()

,1stFlrSF,2ndFlrSF,BedroomAbvGr,BsmtExposure,BsmtFinSF1,BsmtFinType1,BsmtUnfSF,EnclosedPorch,GarageArea,GarageFinish,...,LotFrontage,MasVnrArea,OpenPorchSF,OverallCond,OverallQual,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd,SalePrice
0,856,854.0,3.0,No,706,GLQ,150,0.0,548,RFn,...,65.0,196.0,61,5,7,856,0.0,2003,2003,208500
1,1262,0.0,3.0,Gd,978,ALQ,284,NaN,460,RFn,...,80.0,0.0,0,8,6,1262,NaN,1976,1976,181500
2,920,866.0,3.0,Mn,486,GLQ,434,0.0,608,RFn,...,68.0,162.0,42,5,7,920,NaN,2001,2002,223500
3,961,NaN,NaN,No,216,ALQ,540,NaN,642,Unf,...,60.0,0.0,35,5,7,756,NaN,1915,1970,140000
4,1145,NaN,4.0,Av,655,GLQ,490,0.0,836,RFn,...,84.0,350.0,84,5,8,1145,NaN,2000,2000,250000

Inspect data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   1stFlrSF       1460 non-null   int64
 1   2ndFlrSF       1374 non-null   float64
 2   BedroomAbvGr   1361 non-null   float64
 3   BsmtExposure   1422 non-null   object
 4   BsmtFinSF1     1460 non-null   int64
 5   BsmtFinType1   1315 non-null   object
 6   BsmtUnfSF      1460 non-null   int64
 7   EnclosedPorch  136 non-null    float64
 8   GarageArea     1460 non-null   int64
 9   GarageFinish   1225 non-null   object
 10  GarageYrBlt    1379 non-null   float64
 11  GrLivArea      1460 non-null   int64
 12  KitchenQual    1460 non-null   object
 13  LotArea        1460 non-null   int64
 14  LotFrontage    1201 non-null   float64
 15  MasVnrArea     1452 non-null   float64
 16  OpenPorchSF    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  OverallQual    1460 non-null   int64
 19  TotalBsmtSF    1460 non-null   int64
 20  WoodDeckSF     155 non-null    float64
 21  YearBuilt      1460 non-null   int64
 22  YearRemodAdd   1460 non-null   int64
 23  SalePrice      1460 non-null   int64
dtypes: float64(7), int64(13), object(4)
memory usage: 273.9+ KB

* There is information for the sale price of 1,460 properties in the data. 
* The data is not balanced - there are indicators with missing observations. Some of these may be at acceptable levels while some have very few number observations such as `EnclosedPorch` or `WoodDeckSF`.
* Missing observations for some features could be imputed by making some assumptions. For example, second floor squarefeet is possibly zero for the missing observations.

Check if there are duplicate entries in data

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [1stFlrSF, 2ndFlrSF, BedroomAbvGr, BsmtExposure, BsmtFinSF1, BsmtFinType1, BsmtUnfSF, EnclosedPorch, GarageArea, GarageFinish, GarageYrBlt, GrLivArea, KitchenQual, LotArea, LotFrontage, MasVnrArea, OpenPorchSF, OverallCond, OverallQual, TotalBsmtSF, WoodDeckSF, YearBuilt, YearRemodAdd, SalePrice]
Index: []

[0 rows x 24 columns]

There are no duplicate entries.

## Load and inspect `inherited_houses` data.

In [ ]:
df_inherit = pd.read_csv(f"inputs/datasets/raw/house-price-20211124T154130Z-001/house-price/inherited_houses.csv")
df_inherit.head()

,1stFlrSF,2ndFlrSF,BedroomAbvGr,BsmtExposure,BsmtFinSF1,BsmtFinType1,BsmtUnfSF,EnclosedPorch,GarageArea,GarageFinish,...,LotArea,LotFrontage,MasVnrArea,OpenPorchSF,OverallCond,OverallQual,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd
0,896,0,2,No,468.0,Rec,270.0,0,730.0,Unf,...,11622,80.0,0.0,0,6,5,882.0,140,1961,1961
1,1329,0,3,No,923.0,ALQ,406.0,0,312.0,Unf,...,14267,81.0,108.0,36,6,6,1329.0,393,1958,1958
2,928,701,3,No,791.0,GLQ,137.0,0,482.0,Fin,...,13830,74.0,0.0,34,5,5,928.0,212,1997,1998
3,926,678,3,No,602.0,GLQ,324.0,0,470.0,Fin,...,9978,78.0,20.0,36,6,6,926.0,360,1998,1998

Check information

In [ ]:
df_inherit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   1stFlrSF       4 non-null      int64
 1   2ndFlrSF       4 non-null      int64
 2   BedroomAbvGr   4 non-null      int64
 3   BsmtExposure   4 non-null      object
 4   BsmtFinSF1     4 non-null      float64
 5   BsmtFinType1   4 non-null      object
 6   BsmtUnfSF      4 non-null      float64
 7   EnclosedPorch  4 non-null      int64
 8   GarageArea     4 non-null      float64
 9   GarageFinish   4 non-null      object
 10  GarageYrBlt    4 non-null      float64
 11  GrLivArea      4 non-null      int64
 12  KitchenQual    4 non-null      object
 13  LotArea        4 non-null      int64
 14  LotFrontage    4 non-null      float64
 15  MasVnrArea     4 non-null      float64
 16  OpenPorchSF    4 non-null      int64
 17  OverallCond    4 non-null      int64
 18  OverallQual    4 non-null      int64
 19  TotalBsmtSF    4 non-null      float64
 20  WoodDeckSF     4 non-null      int64
 21  YearBuilt      4 non-null      int64
 22  YearRemodAdd   4 non-null      int64
dtypes: float64(7), int64(12), object(4)
memory usage: 868.0+ bytes

As expected, there are four properties listed in this data. There is no missing information, which will be welcomed during the prediction stage.

---

# Push files to Repo

There has been no changes made in the original data files yet. However, the files will still be copied into an outputs/datasets/collection folder to ensure replicability in cases where an update is made.

In [ ]:
try:
  os.makedirs(name='outputs/datasets/collection')
except Exception as e:
  print(e)

df.to_csv(f"outputs/datasets/collection/house_prices_records.csv", index=False)
df_inherit.to_csv(f"outputs/datasets/collection/inherited_houses.csv", index=False)

# Conclusions and Next Steps

There has been no changes in the raw data downloaded. There are some missing observations in the `house_prices_records` data, which will have to be taken into consideration during model fitting.